# Generated by Django 4.0.10 on 2023-07-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='show_supervisors',
            field=models.BooleanField(default=True),
        ),
    ]
