# Generated by Django 4.0.10 on 2023-07-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_show_supervisors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_name',
            field=models.CharField(max_length=244, verbose_name='Position name'),
        ),
    ]
